sudo: required
language: cpp
compiler:
  - gcc
jobs:
  include:
    - stage: AnacondaEnv
      script: Tests/Training/AnacondaEnv/testSetupCpuEnv.sh
    - stage: Ops
      script: Tests/Training/Ops/buildOps.sh
  only:
    - master
notifications:
  email:
    recipients:
      - mkomm@cern.ch
    on_success: change
    on_failure: always


