sudo: required
language: cpp
compiler:
  - gcc
script:
   - Tests/Training/AnacondaEnv/testSetupCpuEnv.sh
   - Tests/Training/Ops/buildOps.sh
notifications:
  email:
    recipients:
      - mkomm@cern.ch
    on_success: change
    on_failure: always


