sudo: required
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-5
        - g++-5
script:
   - Tests/Training/AnacondaEnv/testSetupCpuEnv.sh
   #- Tests/Training/Ops/buildOps.sh
notifications:
  email:
    recipients:
      - mkomm@cern.ch
    on_success: change
    on_failure: always


