sudo: required
language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get install coreutils
jobs:
  include:
    - stage: AnacondaEnv
      script: Tests/Training/AnacondaEnv/testSetupCpuEnv.sh
  only:
    - master
notifications:
  email:
    recipients:
      - mkomm@cern.ch
    on_success: change
    on_failure: always


